# Simple workflow for deploying static content to GitHub Pages
name: Build and Deploy to Web

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v14

    - name: Build with CMake
      run: |
        emcmake cmake -B build
        cmake --build build

    - name: Deploy to Web Branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout web || git checkout --orphan web
        git rm -rf .
        cp -r build/* .
        git add .
        git commit -m "Automated WebAssembly build"
        git push origin web --force
